name: Reusable

on:
  workflow_call:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        default: "Mona the Octocat"
        type: string
      greeting:
        description: "Greeting to use"
        required: true
        default: "Hello"
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Greet
        run: sh ./dir-a/script.sh ${{ inputs.greeting }} ${{ inputs.name }}
