name: Reusable

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'Mona the Octocat'
        type: string
      greeting:
        description: 'Greeting to use'
        required: true
        default: 'Hello'
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Greet
        run: sh ./dir-a/script.sh ${{ inputs.greeting }} ${{ inputs.name }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "${ALL_CHANGED_FILES}"
