name: Reusable

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'Mona the Octocat'
        type: string
      greeting:
        description: 'Greeting to use'
        required: true
        default: 'Hello'
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Greet
        run: sh ./dir-a/script.sh ${{ inputs.greeting }} ${{ inputs.name }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_yaml_from_source_file: .github/changed-files.yml

      - name: List all changed files
        env:
          A_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.dir-a_all_changed_files }}
          B_C_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.dir-b-c_all_changed_files }}
          B_D_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.dir-b-d_all_changed_files }}
          OTHERS_ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.others_all_changed_files }}
        run: |
          bash .github/script.sh "${A_ALL_CHANGED_FILES}" "${B_C_ALL_CHANGED_FILES}" "${B_D_ALL_CHANGED_FILES}" "${{ steps.changed-files.outputs.dir-a_any_changed }}"
          echo "---"
          echo "${OTHERS_ALL_CHANGED_FILES}"
