on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            dir-a
            dir-b/c
      
      - name: tree
        run: tree
