on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  sandbox:
    uses: midorimici/github-actions-sandbox/.github/workflows/reusable.yml@main
    with:
      greeting: Hello
      name: World
