on:
  push:
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Git status
        run: |
          git log --oneline --graph --branches --all
          git diff @ @~
