on:
  push:
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox

    runs-on: ubuntu-latest

    env:
      ARTIFACT_DIR_PATH: /tmp/artifacts

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create files
        run: |
          echo "Hello" > hello.txt
          echo "world" > world.txt
          mkdir ${{ env.ARTIFACT_DIR_PATH }}
          echo "log" > ${{ env.LOG_FILE_PATH }}
        env:
          LOG_FILE_PATH: ${{ env.ARTIFACT_DIR_PATH }}/log

      - name: List new files
        run: git ls-files --others --exclude-standard

      - name: Move the file to artifact directory
        run: |
          mv $(git ls-files --others --exclude-standard) ${{ env.ARTIFACT_DIR_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: ${{ env.ARTIFACT_DIR_PATH }}
          if-no-files-found: error
