on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Release tag name
        run: echo "${{ startsWith(github.event.release.tag_name, 'release') }}"
