on:
  pull_request:
  issue_comment:
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List attached labels
        run: echo "${{ toJSON((github.event.pull_request||github.event.issue).labels) }}"
