on:
  pull_request:
  issue_comment:
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check event
        run: echo "${{ toJSON(github.event) }}"
